#!/usr/bin/env bash
# Regenerates the three embeddable widget pages from their full tool pages.
#
# Why a generator instead of three hand-maintained copies: the widget IS the
# tool, minus page chrome. Hand-copying guarantees the two drift apart the
# first time a tool is touched, and a stale widget is worse than none because
# it is already live on somebody else's site. Same principle as the tap-tempo
# tempo table being sourced from MetronomeScreen.kt and the odd meter tool
# porting Meter.kt: one source, no second copy to forget.
#
# Run from the repo root after changing any file in landing/tools/:
#   bash landing/embed/build-embeds.sh
#
# The generated .html files ARE committed. This is not a Vercel build step;
# the site stays fully static.

set -euo pipefail
cd "$(dirname "$0")/../.."
TOOLS="landing/tools"
OUT="landing/embed"

# Everything between <section class="tool-panel" ...> and its closing
# </section>, with the attribution line injected just INSIDE the panel.
#
# Inside, not after: the panel is the only element with a background of its
# own. The body is transparent so the panel's rounded corners show the host
# page through them, which means anything sitting outside the panel is
# painted on an unknown background. A credit line in near-white on a white
# lesson page is an invisible credit line, and the credit is the entire
# reason these widgets are free.
extract_panel() {
  awk -v credit="$2" '
    /<section class="tool-panel"/{f=1}
    f && /<\/section>/ && !done { print credit; done=1 }
    f{print}
    f && done {exit}
  ' "$1"
}

# The page's own behaviour script: the bare `  <script>` block, never the
# earlier `<script type="application/ld+json">` schema blocks.
extract_script() {
  awk '/^  <script>$/{f=1} f{print} f&&/^  <\/script>$/{exit}' "$1"
}

emit() {
  local src="$1" out="$2" title="$3" canonical="$4" anchor="$5" extra="$6"

  {
    cat <<HEAD
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
  <!-- Widget build of ${canonical}. Generated by landing/embed/build-embeds.sh -
       do not edit by hand, edit the tool page and re-run the script.
       noindex keeps a thin duplicate out of the index; follow keeps the
       attribution links below flowing equity back to the full tool. -->
  <meta name="robots" content="noindex, follow">
  <link rel="canonical" href="${canonical}">
  <link rel="icon" type="image/webp" href="/favicon.webp">
  <link rel="stylesheet" href="/blog/style.css">
  <link rel="stylesheet" href="/embed/style.css">
</head>
<body class="embed-body">

HEAD

    credit=$(printf '      <p class="embed-credit">\n        <a href="%s?ref=embed" target="_blank" rel="noopener">%s</a>\n        by <a href="https://metrognome.co.za/?ref=embed" target="_blank" rel="noopener">Metro Gnome</a>\n      </p>' "$canonical" "$anchor")
    extract_panel "$src" "$credit"
    echo

    # Some tools read reference data out of a table that lives in the page
    # prose. The prose is dropped here, so the table travels with the widget,
    # hidden, rather than the script silently losing a feature.
    if [ -n "$extra" ]; then
      echo '  <div hidden aria-hidden="true">'
      echo '    <table><tbody id="'"$extra"'">'
      sed -n "/<tbody id=\"${extra}\">/,/<\/tbody>/p" "$src" | sed '1d;$d'
      echo '    </tbody></table>'
      echo '  </div>'
      echo
    fi

    extract_script "$src"

    cat <<'TAIL'

</body>
</html>
TAIL
  } > "$out"

  echo "wrote $out ($(wc -l < "$out") lines)"
}

emit "$TOOLS/odd-meter-practice-tool.html" "$OUT/odd-meter.html" \
  "Odd Meter Metronome - Metro Gnome" \
  "https://metrognome.co.za/tools/odd-meter-practice-tool.html" \
  "Odd meter metronome" ""

emit "$TOOLS/tap-tempo-bpm-finder.html" "$OUT/tap-tempo.html" \
  "Tap Tempo BPM Finder - Metro Gnome" \
  "https://metrognome.co.za/tools/tap-tempo-bpm-finder.html" \
  "Tap tempo BPM finder" "markingTableBody"

emit "$TOOLS/rhythm-timing-test.html" "$OUT/rhythm-test.html" \
  "Rhythm Timing Test - Metro Gnome" \
  "https://metrognome.co.za/tools/rhythm-timing-test.html" \
  "Rhythm timing test" ""
